name: Deploy to git

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0' # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install # Use yarn if you prefer

      - name: Build the Vite application
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.DEV_API_BASE_URL }}" >> .env
          npm run build # Replace with the build script used in your Vite project

  